### ISSUE TITLE
Kontrola 8

### ISSUE THREAD

**Issue by mcurlej** [nappex/DU_8_slovniky#1]
Ahoj,

toto by sa dalo napisat jednoduchsie

https://github.com/nappex/DU_8_slovniky/blob/master/uloha_4.py#L12-L21

napr:

```python
    for otazka in seznam_otazek
        odpoved = input("Zadej odpoved na otazku " + otazka + " nebo "
                          "zadej \"konec\":\n")
        if odpoved.lower().strip() == "konec":
            break
    
        seznam_odpovedi.append(odpoved.lower().strip())
            
        slovnik_odpovedi[otazka] = list(seznam_odpovedi)
        seznam_odpovedi.clear()
```
Vzdy ked chces niekde pridat vnoreny cyklus zamysli sa ze zlozitost kodu vzrasta exponencionalne. V tvojom pripade while cyklus bol zbytocny. Ty je to trochu vysvetlene (ale je to anglicky... :)) https://stackoverflow.com/questions/526728/time-complexity-of-nested-for-loop

Inac zvysok je ok.

**Comment by mcurlej** [comment]
@frenzymadness kukni na hento vyssie, maju to viacery ze davaju dalsi cyklus do vnutra toho prveho, vacsinou je to dost zbytocne

**Comment by frenzymadness** [comment]
Vnořený cyklus je zde naprosto v pořádku, protože ty se chceš uživatele zeptat na každou otázku vícekrát dokud ti neodpoví "konec" a pak se přesunout na další otázku.

**Comment by mcurlej** [comment]
k nevsimol som si tak potom nic k tomu asi.
